export const FETCH_USER = 'FETCH_USER';

export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const FETCH_SURVEYS_LOADER = 'FETCH_SURVEYS_LOADER';
export const DELETE_SURVEY = 'DELETE_SURVEY';
export const SORT_SURVEYS = 'SORT_SURVEYS';
export const SEND_SURVEY_LOADER = 'SEND_SURVEY_LOADER';
export const SENT_SURVEY = 'SENT_SURVEY';

export const FETCH_DRAFTS_LOADER = 'FETCH_DRAFTS_LOADER';
export const FETCH_DRAFTS = 'FETCH_DRAFTS';
export const ADD_DRAFT = 'ADD_DRAFT';
export const DELETE_DRAFT = 'DELETE_DRAFT';
export const SORT_DRAFTS = 'SORT_DRAFTS';
export const EDIT_DRAFT = 'EDIT_DRAFT';
export const CHANGE_DRAFT = 'CHANGE_DRAFT';
export const SHOW_DRAFT_LOADER = 'SHOW_DRAFT_LOADER';
export const SET_DRAFT_ID = 'SET_DRAFT_ID';