export const SET_SERVER_ERROR = 'SET_SERVER_ERROR';
export const REMOVE_SERVER_ERROR = 'REMOVE_SERVER_ERROR';

export const FETCH_ADMIN = 'FETCH_ADMIN';
export const FETCH_ADMIN_SUCCESS = 'FETCH_ADMIN_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';

export const FETCH_SKILLS = 'FETCH_SKILLS';
export const FETCH_SKILLS_SUCCESS = 'FETCH_SKILLS_SUCCESS';

export const RESET_SKILLS = 'RESET_SKILLS';

export const ADD_SKILL = 'ADD_SKILL';
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const REMOVE_SKILL = 'REMOVE_SKILL';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';

export const SAVE_SKILLS = 'SAVE_SKILLS';
export const SAVE_SKILLS_START = 'SAVE_SKILLS_START';
export const SAVE_SKILLS_SUCCESS = 'SAVE_SKILLS_SUCCESS';

export const UPDATE_SKILL = 'UPDATE_SKILL';

export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_START = 'CREATE_PROJECT_START';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';

export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT';

export const EDIT_PROJECT = 'EDIT_PROJECT';
export const EDIT_PROJECT_START = 'EDIT_PROJECT_START';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';

export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const REMOVE_PROJECT_SUCCESS = 'REMOVE_PROJECT_SUCCESS';

export const FETCH_TECHS = 'FETCH_TECHS';
export const FETCH_TECHS_SUCCESS = 'FETCH_TECHS_SUCCESS';

export const ADD_TECH = 'ADD_TECH';
export const ADD_TECH_SUCCESS = 'ADD_TECH_SUCCESS';
export const ADD_TECH_START = 'ADD_TECH_START';

export const REMOVE_TECH = 'REMOVE_TECH';
export const REMOVE_TECH_SUCCESS = 'REMOVE_TECH_SUCCESS';

export const FETCH_EMAILS = 'FETCH_EMAILS';
export const FETCH_EMAILS_SUCCESS = 'FETCH_EMAILS_SUCCESS';

export const SEND_EMAIL = 'SEND_EMAIL';
export const SEND_EMAIL_START = 'SEND_EMAIL_START';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';

export const REMOVE_EMAIL = 'REMOVE_EMAIL';
export const REMOVE_EMAIL_SUCCESS = 'REMOVE_EMAIL_SUCCESS';

export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';

export const EDIT_CONTACTS = 'EDIT_CONTACTS';
export const EDIT_CONTACTS_START = 'EDIT_CONTACTS_START';

export const ADD_IMAGE = 'ADD_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const IMAGE_START = 'IMAGE_START';
